doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
#        add date to orm dql
        dql:
            string_functions:
                DATE: DoctrineExtensions\Query\Mysql\Date
                YEAR: DoctrineExtensions\Query\Mysql\Year
                MONTH: DoctrineExtensions\Query\Mysql\Month
                DAY: DoctrineExtensions\Query\Mysql\Day
                HOUR: DoctrineExtensions\Query\Mysql\Hour
                MINUTE: DoctrineExtensions\Query\Mysql\Minute
                SECOND: DoctrineExtensions\Query\Mysql\Second
                WEEK: DoctrineExtensions\Query\Mysql\Week
                QUARTER: DoctrineExtensions\Query\Mysql\Quarter
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                DATE_ADD: DoctrineExtensions\Query\Mysql\DateAdd
                DATE_SUB: DoctrineExtensions\Query\Mysql\DateSub
                DATE_DIFF: DoctrineExtensions\Query\Mysql\DateDiff
                DATE_TRUNC: DoctrineExtensions\Query\Mysql\DateTrunc
                DATE_MOD: DoctrineExtensions\Query\Mysql\DateMod
                SOUNDEX: DoctrineExtensions\Query\Mysql\Soundex

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
            mapping_types:
                enum: string

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
